name: manro_msg
description: A custom Flutter messenger by Emil

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  http: ^0.13.6

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.5
  firebase_messaging: 14.7.10
  firebase_storage: ^11.6.6
  image_picker: ^1.0.4

  flutter_local_notifications: 14.0.1
  uuid: ^3.0.7   # ✅ Добавлено для генерации sessionId

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/menro-icon.png
  remove_alpha_ios: true