// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SvIbRm2Q0yNlsec1XeCL4cYIrCYDQyA',
    appId: '1:172648164282:web:630c03fc1a0c8a7fd58b83',
    messagingSenderId: '172648164282',
    projectId: 'menro-msg',
    authDomain: 'menro-msg.firebaseapp.com',
    storageBucket: 'menro-msg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKD8IASGfXlguWTbg0CQbjfrnhRHld8RA',
    appId: '1:172648164282:android:ba9d1e017297e1b1d58b83',
    messagingSenderId: '172648164282',
    projectId: 'menro-msg',
    storageBucket: 'menro-msg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-XvSF0emMdH1JfIt73X_7LP1k6EY2x8s',
    appId: '1:172648164282:ios:201c8fc41885f444d58b83',
    messagingSenderId: '172648164282',
    projectId: 'menro-msg',
    storageBucket: 'menro-msg.firebasestorage.app',
    iosBundleId: 'com.example.manroMsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-XvSF0emMdH1JfIt73X_7LP1k6EY2x8s',
    appId: '1:172648164282:ios:201c8fc41885f444d58b83',
    messagingSenderId: '172648164282',
    projectId: 'menro-msg',
    storageBucket: 'menro-msg.firebasestorage.app',
    iosBundleId: 'com.example.manroMsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SvIbRm2Q0yNlsec1XeCL4cYIrCYDQyA',
    appId: '1:172648164282:web:c756d0280003a751d58b83',
    messagingSenderId: '172648164282',
    projectId: 'menro-msg',
    authDomain: 'menro-msg.firebaseapp.com',
    storageBucket: 'menro-msg.firebasestorage.app',
  );

}